### PR TITLE
Adding support for Web Scenario creation.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
The goal of this is to be able to configure a Zabbix server. Our current
needs are to have a docker image that can be run as a post deploy hook
to configure web scenarios (http checks) of a number of http services
that expose a ping url.

Modifications:
Added fh-zabbix.js module and run.sh which uses the module.

Result:
An buildable Docker image which can be run as a post deploy hook when
deploying a Zabbix container.

JIRA:
https://issues.jboss.org/browse/RHMAP-2765

### CODE REVIEW

**Comment by grdryn** [comment]
Retest this please.

**Comment by grdryn** [comment]
Retest this please.

**Comment by danbev** [comment]
@grdryn Thanks for fixing the CI job!

**Comment by grdryn** [comment]
@danbev no problem. I had to get it to run twice, because Jenkins ran out of inodes again and couldn't do the npm install.

**Comment by danbev** [comment]
Closing this PR as we've decided to take a different approach. See [comment](https://issues.jboss.org/browse/RHMAP-2756?focusedCommentId=13129565&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13129565) for details.

**Pull request closed without merging**
